# Generated by Django 5.2.3 on 2025-09-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_desk', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketComment',
        ),
    ]
