# Generated by Django 5.2.3 on 2025-09-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_desk', '0002_delete_ticketcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'OPEN'), ('in-progress', 'IN PROGRESS'), ('resolved', 'RESOLVED'), ('closed', 'CLOSED'), ('escalated', 'ESCALATED')], default='open', max_length=25),
        ),
    ]
